CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS users ( id SERIAL PRIMARY KEY, email VARCHAR(255) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(32) NOT NULL, created_at TIMESTAMP DEFAULT NOW() NOT NULL );
CREATE TABLE IF NOT EXISTS jobs ( id SERIAL PRIMARY KEY, title VARCHAR(255) NOT NULL, department VARCHAR(255), description TEXT, created_at TIMESTAMP DEFAULT NOW() NOT NULL );
CREATE TABLE IF NOT EXISTS candidates ( id SERIAL PRIMARY KEY, full_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(32), cv_url TEXT, created_at TIMESTAMP DEFAULT NOW() NOT NULL );
CREATE TABLE IF NOT EXISTS audit_logs ( id SERIAL PRIMARY KEY, user_id INT, action VARCHAR(128) NOT NULL, entity VARCHAR(64), entity_id INT, ip VARCHAR(64), created_at TIMESTAMP DEFAULT NOW() NOT NULL );
CREATE TABLE IF NOT EXISTS booking_links ( id SERIAL PRIMARY KEY, token VARCHAR(128) UNIQUE NOT NULL, job_id INT, candidate_id INT, expires_at TIMESTAMP NOT NULL, scheduled_at TIMESTAMP, created_at TIMESTAMP DEFAULT NOW() NOT NULL, used BOOLEAN DEFAULT FALSE NOT NULL );
